version: '2'
services:
  decidim:
    image: jsperezg/decidim
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    entrypoint: ["/code/bin/entrypoint.sh"]
    command: bundle exec rails s -b 0.0.0.0
  worker:
    image: jsperezg/decidim-worker
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
      - RAILS_SERVE_STATIC_FILES=1
      # - RAILS_FORCE_SSL=1
    links:
      - pg
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  pg-data: {}
  redis-data: {}
